services:
  - type: web_service
    name: makemytrip-backend
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: starter

  - type: web_service
    name: makemytour-frontend
    env: node
    branch: main
    rootDir: makemytour
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    plan: starter
