spring.application.name=makemytrip
server.port=8080

spring.data.mongodb.uri=mongodb+srv://user:user123@main.ukserpr.mongodb.net/makemytrip?retryWrites=true&w=majority&appName=main

spring.data.mongodb.database=makemytrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
